// DEBT.md: every row that did not reach parity, regenerated by the recorder.
//
// A `debt` row is a real mismatch between fireemu and the official emulator that
// nobody has decided about yet. It never fails `pnpm run check` -- gating on it would only
// freeze the mismatch -- but it is listed here so that a claim of parity cannot be made while
// it stands. A `pending` row is a question no local oracle can answer at all.

import { STATUS } from "./config.mjs";

const brief = (value) => {
  const text = JSON.stringify(value);
  return text.length > 240 ? `${text.slice(0, 237)}...` : text;
};

export function renderDebtDoc(fixtures) {
  const debt = [];
  const pending = [];
  const divergences = [];
  for (const fixture of fixtures) {
    for (const step of fixture.steps) {
      const row = { fixture: fixture.id, product: fixture.product, step };
      if (step.status === STATUS.debt) debt.push(row);
      else if (step.status === STATUS.pending) pending.push(row);
      else if (step.status === STATUS.documentedDivergence) divergences.push(row);
    }
  }

  const debtSection =
    debt.length === 0
      ? "_No undocumented mismatch is outstanding._"
      : debt
          .map(
            ({ fixture, step }) =>
              `### \`${fixture}#${step.id}\`\n\n` +
              `- oracle: \`${brief(step.oracle)}\`\n` +
              `- fireemu: \`${brief(step.testd)}\`\n`,
          )
          .join("\n");

  const pendingSection =
    pending.length === 0
      ? "_No pending row._"
      : pending
          .map(
            ({ fixture, step }) =>
              `### \`${fixture}#${step.id}\`\n\n` +
              `- reason: **${step.reason}**\n` +
              `- what a real project would settle: ${step.production}\n`,
          )
          .join("\n");

  const divergenceSection =
    divergences.length === 0
      ? "_No documented divergence._"
      : divergences
          .map(
            ({ fixture, step }) =>
              `- \`${fixture}#${step.id}\` -- ${step.reason}  \n  documented in: ${step.documents}`,
          )
          .join("\n");

  return `# Conformance debt

<!-- Generated by \`pnpm -C conformance run oracle\`. Do not edit by hand; to move a row out of
     debt, describe it in \`conformance/divergences.json\` and re-record. -->

Three kinds of row appear here, and none of them fails \`pnpm -C conformance run check\`:

- **debt** -- fireemu and the official emulator disagree and nobody has decided whether
  the difference is intended. Until a row leaves this list, no parity claim may cover it.
- **pending** -- no local oracle can answer the row. The official emulators cannot produce the
  behaviour, so the row is recorded with a reason and never with an invented result.
- **documented divergence** -- a difference that is intended and written down. These are listed
  for completeness; \`check\` does gate them, against the recorded fireemu value.

## Debt (${debt.length})

${debtSection}

## Pending: needs a real project (${pending.length})

${pendingSection}

## Documented divergences (${divergences.length})

${divergenceSection}

## Standing proposal: precision of the App Check boundary rows

\`APPCHECK-ENFORCE-1\` and \`APPCHECK-FUNCTIONS-1\` are published as \`boundary-conformance\`
because \`docs/specifications/firebase-app-check.md\` section 17 makes the wire mappings
provisional "until the conformance scenarios record and approve the corresponding real-service
behavior", and section 23 keeps the exact Firestore, Storage and Auth messages on the debt list.

This suite does **not** discharge that. Its oracle is the official Local Emulator Suite, which
implements no App Check at all, so it can record that the official emulators never enforce -- and
it does -- but it cannot record what a real project denies. Raising either entry to \`exact\`
therefore needs evidence this suite cannot produce.

Proposal, recorded here rather than acted on: add a second, credentialed oracle that runs the
\`appcheck/*\` scenarios against a real Firebase project with enforcement enabled, gated behind an
explicit opt-in and a project the maintainer owns, and re-record the \`pending\` rows above from
it. Only with those fixtures approved would the section 17 mappings become \`exact\`.
`;
}
