// Oracle provenance: what exactly answered as "the official emulator" on this run.
//
// Nothing here is typed by hand. The version and integrity of `firebase-tools` come from the
// installed package and the lockfile, and the bundled emulator versions and checksums come
// from the CLI's own `downloadableEmulatorInfo.json`, so ORACLE.md cannot drift away from the
// tree that produced the fixtures.

import { createHash } from "node:crypto";
import { readFile, stat } from "node:fs/promises";
import { createRequire } from "node:module";
import { homedir } from "node:os";
import { join } from "node:path";

import { CONFORMANCE_DIR } from "./config.mjs";

export {
  classifyProductionCase,
  collectEvidence,
  digestFile,
  digestJson,
  evidenceIdentity,
  resolveFireemuBinary,
  summarizeStatuses,
  validateRecordedExpectation,
  validateEvidenceJoin,
  validateLiveEvidence,
} from "./evidence.mjs";

const require = createRequire(join(CONFORMANCE_DIR, "package.json"));

const readJson = async (path) => JSON.parse(await readFile(path, "utf8"));

/** The integrity string pnpm recorded for the pinned CLI, if a lockfile is present. */
async function lockfileIntegrity(specifier) {
  try {
    const lock = await readFile(join(CONFORMANCE_DIR, "pnpm-lock.yaml"), "utf8");
    const marker = `${specifier}:`;
    const index = lock.indexOf(marker);
    if (index < 0) return null;
    const window = lock.slice(index, index + 600);
    const match = window.match(/integrity:\s*(sha\d{3}-[A-Za-z0-9+/=]+)/);
    return match?.[1] ?? null;
  } catch {
    return null;
  }
}

/** SHA-256 over the installed package's own manifest: a local, verifiable identity. */
async function installedDigest(packageJsonPath) {
  const bytes = await readFile(packageJsonPath);
  return `sha256-${createHash("sha256").update(bytes).digest("hex")}`;
}

export async function collectProvenance() {
  const declared = await readJson(join(CONFORMANCE_DIR, "package.json"));
  const toolsManifestPath = require.resolve("firebase-tools/package.json");
  const tools = await readJson(toolsManifestPath);
  const info = require("firebase-tools/lib/emulator/downloadableEmulatorInfo.json");

  const flatten = (name, node) => {
    if (node?.version) return [{ name, ...node }];
    if (node && typeof node === "object") {
      return Object.entries(node).flatMap(([key, child]) => flatten(`${name}.${key}`, child));
    }
    return [];
  };
  const emulators = Object.entries(info)
    .flatMap(([name, node]) => flatten(name, node))
    .map((e) => ({
      name: e.name,
      version: e.version,
      sha256: e.expectedChecksumSHA256 ?? null,
      md5: e.expectedChecksum ?? null,
      remoteUrl: e.remoteUrl ?? null,
    }))
    .toSorted((a, b) => (a.name < b.name ? -1 : 1));

  const cacheDir =
    process.env.FIREBASE_EMULATORS_PATH ?? join(homedir(), ".cache/firebase/emulators");
  const cached = [];
  for (const emulator of emulators) {
    const relative = flattenPath(info, emulator.name);
    if (!relative) continue;
    try {
      const info2 = await stat(join(cacheDir, relative));
      cached.push({ name: emulator.name, file: relative, bytes: info2.size });
    } catch {
      // Not downloaded on this machine; the run either did not need it or fetched it later.
    }
  }

  return {
    declared: declared.dependencies,
    firebaseTools: {
      version: tools.version,
      integrity: await lockfileIntegrity(
        `firebase-tools@${declared.dependencies["firebase-tools"]}`,
      ),
      manifestDigest: await installedDigest(toolsManifestPath),
    },
    node: process.version,
    platform: `${process.platform}-${process.arch}`,
    emulators,
    cached,
  };
}

function flattenPath(info, name) {
  const node = name.split(".").reduce((acc, key) => acc?.[key], info);
  return node?.downloadPathRelativeToCacheDir ?? null;
}

/** ORACLE.md, regenerated on every `pnpm run oracle`. */
export function renderOracleDoc(provenance, { scenarioCount, stepCount }) {
  const rows = provenance.emulators
    .map((e) => `| \`${e.name}\` | ${e.version} | ${e.sha256 ? `\`${e.sha256}\`` : "n/a"} |`)
    .join("\n");
  const declared = Object.entries(provenance.declared)
    .map(([name, version]) => `| \`${name}\` | \`${version}\` |`)
    .join("\n");

  return `# Conformance oracle

<!-- Generated by \`pnpm -C conformance run oracle\`. Do not edit by hand. -->

The oracle for this suite is the official Local Emulator Suite as shipped by a single pinned
\`firebase-tools\` release. Every fixture under \`conformance/fixtures/\` was recorded against the
versions below; a fixture recorded against anything else is not comparable, which is why this
file is regenerated by the recorder rather than maintained by hand.

## Pinned packages

Exact versions, no ranges. \`conformance/package.json\` pins them and \`pnpm-lock.yaml\` pins their
integrity.

| Package | Version |
| --- | --- |
${declared}

\`firebase-tools\` resolved to **${provenance.firebaseTools.version}**.

- lockfile integrity: ${provenance.firebaseTools.integrity ? `\`${provenance.firebaseTools.integrity}\`` : "not recorded (no lockfile present at record time)"}
- installed manifest digest: \`${provenance.firebaseTools.manifestDigest}\`

## Bundled emulator artifacts

These are the downloadable emulators \`firebase-tools ${provenance.firebaseTools.version}\` fetches
and their upstream checksums, read from the CLI's own \`downloadableEmulatorInfo.json\`. The suite
uses \`firestore\` and \`storage\`; the rest are listed so an upstream bump is visible as a diff.

| Emulator | Version | SHA-256 |
| --- | --- | --- |
${rows}

Cached on the machine that recorded the fixtures:

${provenance.cached.length === 0 ? "_none (the recorder downloaded them into a clean cache)_" : provenance.cached.map((c) => `- \`${c.file}\` (${c.bytes} bytes)`).join("\n")}

## Recording environment

- Node: \`${provenance.node}\`
- Platform: \`${provenance.platform}\`
- Java: required by the Firestore emulator; the recorder fails rather than skipping if it is absent.

## Corpus

${scenarioCount} scenarios, ${stepCount} recorded steps.

## What the oracle cannot answer

The official emulators implement no App Check surface: no exchange endpoint, no JWKS route and
no inspection of \`X-Firebase-AppCheck\`. Rows that would need production behaviour are recorded
as \`pending\` with the reason "needs a real project" and are never compared. See \`DEBT.md\`.
`;
}
