// The curated half of the Security Rules language matrix (RULES-PARITY-01).
//
// Every entry is a *claim*: one boolean Rules expression whose verdict the pinned official
// runtime adjudicates. A claim is compiled into two `match` blocks -- one guarded by the
// claim, one by its negation -- so a run separates the three outcomes the language has:
//
//   true    the positive block allowed and the negated block denied
//   false   the negated block allowed and the positive block denied
//   error   both denied: the expression raised, or produced a non-boolean
//
// Nothing here asserts what the answer *should* be. The oracle decides, the answer is
// recorded, and fireemu has to reproduce it. A claim whose recorded verdict is `error` is
// as much a parity obligation as one that is `true`.
//
// The `/` of a division must be surrounded by spaces: the official lexer reads `1/0` as a
// path literal and the whole file then fails to compile.

/** @typedef {{ id: string, area: string, claim: string, note?: string }} Claim */

/** @type {Record<string, string[]>} */
const AREAS = {
  // ---------------------------------------------------------------- types and `is`
  type_is: [
    "1 is int",
    "1 is float",
    "1 is number",
    "1.0 is float",
    "1.0 is int",
    "1.0 is number",
    "'a' is string",
    "true is bool",
    "[] is list",
    "{} is map",
    "null is null",
    "request.time is timestamp",
    "duration.value(1, 's') is duration",
    "latlng.value(1.0, 2.0) is latlng",
    "path('/a/b') is path",
    "'a'.toUtf8() is bytes",
    "[1, 2].toSet() is set",
    "[1, 2].toSet() is list",
    "{'a': 1}.diff({'b': 2}).addedKeys() is set",
    "{'a': 1}.diff({'b': 2}).addedKeys() is list",
    "null is int",
    "null is map",
    "1 is string",
    "1 is bogus",
    "request.auth is map",
  ],

  // ---------------------------------------------------------------- equality and ordering
  comparison: [
    "1 == 1.0",
    "1 != 1.0",
    "1 < 1.5",
    "2 > 1.5",
    "1 <= 1",
    "'a' < 'b'",
    "'A' < 'a'",
    "'' < 'a'",
    "[1] == [1]",
    "[1, 2] == [2, 1]",
    "{'a': 1} == {'a': 1}",
    "{'a': 1} == {'a': 1.0}",
    "null == null",
    "null != 1",
    "1 == '1'",
    "true == 1",
    "true == true",
    "[1, 2] < [1, 3]",
    "{'a': 1} < {'a': 2}",
    "1 < 'a'",
    "null < 1",
    "'a'.toUtf8() == 'a'.toUtf8()",
    "'a'.toUtf8() < 'b'.toUtf8()",
    "path('/a') == path('/a')",
    "path('/a') < path('/b')",
    "latlng.value(1.0, 2.0) == latlng.value(1.0, 2.0)",
    "duration.value(1, 's') == duration.value(1000, 'ms')",
    "duration.value(1, 's') < duration.value(2, 's')",
    "[1, 2].toSet() == [2, 1].toSet()",
    "[1, 2].toSet() == [1, 2]",
    "[1, 1, 2].toSet() == [1, 2].toSet()",
  ],

  // ---------------------------------------------------------------- arithmetic
  arithmetic: [
    "1 + 2 == 3",
    "1 - 2 == -1",
    "2 * 3 == 6",
    "5 / 2 == 2",
    "-5 / 2 == -2",
    "5 / 2 is int",
    "5.0 / 2 == 2.5",
    "5 % 3 == 2",
    "-5 % 3 == -2",
    "5 % -3 == 2",
    "1 / 0 == 1",
    "1 % 0 == 1",
    "1.0 / 0.0 == 1.0",
    "math.isInfinite(1.0 / 0.0)",
    "9223372036854775807 + 1 == 0",
    "-9223372036854775807 - 2 == 0",
    "9223372036854775807 * 2 == 0",
    "-9223372036854775807 - 1 == -9223372036854775808",
    "-(-9223372036854775807) == 9223372036854775807",
    "1 + 1.5 == 2.5",
    "1.5 + 1 == 2.5",
    "1 + true == 2",
    "1 + null == 1",
    "'a' + 1 == 'a1'",
    "1 + 'a' == '1a'",
  ],

  // ---------------------------------------------------------------- string
  string: [
    "'abc'.size() == 3",
    "'\\u00e9'.size() == 1",
    "'ABC'.lower() == 'abc'",
    "'abc'.upper() == 'ABC'",
    "'  a  '.trim() == 'a'",
    "'a,b'.split(',') == ['a', 'b']",
    "'abc'.split('') == ['a', 'b', 'c']",
    "'a'.split(',') == ['a']",
    "'abc' + 'def' == 'abcdef'",
    "'abc'[0] == 'a'",
    "'abc'[3] == 'a'",
    "'abc'[-1] == 'c'",
    "'abcdef'[1:3] == 'bc'",
    "'abcdef'[0:0] == ''",
    "'abcdef'[4:2] == ''",
    "'abcdef'[0:99] == 'abcdef'",
    "'abc'.toUtf8().size() == 3",
    "'abc'.toUtf8().toBase64() == 'YWJj'",
    "'abc'.toUtf8().toHexString() == '616263'",
    "'a'.replace('a', 'b') == 'b'",
    "'aaa'.replace('a', 'b') == 'bbb'",
    "'abc'.replace('(a)(b)', '$2$1') == 'bac'",
    "'abc'.replace('(a)(b)', '\\\\2\\\\1') == 'bac'",
    "string(1) == '1'",
    "string(1.5) == '1.5'",
    "string(true) == 'true'",
    "string(null) == 'null'",
    "string(path('/a/b')) == '/a/b'",
    "int('12') == 12",
    "int('12abc') == 12",
    "int(' 12 ') == 12",
    "int(1.9) == 1",
    "int(-1.9) == -1",
    "int(true) == 1",
    "float('1.5') == 1.5",
    "float(1) == 1.0",
    "bool('true') == true",
    "bytes('abc').size() == 3",
  ],

  // ---------------------------------------------------------------- matches / regex dialect
  regex: [
    "'abc'.matches('a.c')",
    "'abc'.matches('b')",
    "'abc'.matches('.*b.*')",
    "'abc'.matches('^abc$')",
    "'abc'.matches('abc|def')",
    "'a1'.matches('[a-z][0-9]')",
    "'a1'.matches('\\\\w+')",
    "'a1'.matches('[[:alpha:]][[:digit:]]')",
    "'ABC'.matches('(?i)abc')",
    "'abc'.matches('a(?=b)c')",
    "'aa'.matches('(a)\\\\1')",
    "'abc'.matches('a{1,2}bc')",
    "'abc'.matches('[')",
    "''.matches('')",
    "'a\\nb'.matches('a.b')",
    "'a\\nb'.matches('(?s)a.b')",
    "'abc'.matches('(?:abc)')",
    "'abc'.matches('a\\\\x62c')",
    "'\\u00e9'.matches('.')",
    "'\\u0000'.matches('\\\\0')",
    "'0'.matches('\\\\0')",
    "'\\\\0'.matches('\\\\0')",
    "'\\u0000\\u0000'.matches('(\\\\0)+')",
    "'\\u0000'.matches('[\\\\0]')",
    "'0'.matches('[^\\\\0]')",
    "'\\u0000'.matches('\\\\00')",
    "'\\u00009'.matches('\\\\09')",
    "'\\u0000'.matches('\\\\000')",
    "'\\u00000'.matches('\\\\0000')",
    "'\\u0001'.matches('\\\\01')",
    "'\\u0001'.matches('\\\\001')",
    "'\\t'.matches('\\\\011')",
    "'\\u00008'.matches('\\\\08')",
  ],

  // ---------------------------------------------------------------- list
  list: [
    "[1, 2, 3].size() == 3",
    "[1, 2, 3].hasAll([1, 2])",
    "[1, 2, 3].hasAll([1, 4])",
    "[1, 2, 3].hasAny([4, 2])",
    "[1, 2, 3].hasOnly([1, 2, 3, 4])",
    "[1, 2, 3].hasOnly([1, 2])",
    "[1, 2].concat([3]) == [1, 2, 3]",
    "['a', 'b'].join(',') == 'a,b'",
    "[1, 2].join(',') == '12'",
    "[1, 2, 3].removeAll([2]) == [1, 3]",
    "[1, 2, 2].removeAll([2]) == [1]",
    "[1, 2].toSet().size() == 2",
    "[1, 2, 3][0] == 1",
    "[1, 2, 3][3] == 1",
    "[1, 2, 3][-1] == 3",
    "[1, 2, 3][0:2] == [1, 2]",
    "[1, 2, 3][1:1] == []",
    "[1, 2, 3][2:1] == []",
    "[1, 2, 3][0:99] == [1, 2, 3]",
    "1 in [1, 2]",
    "4 in [1, 2]",
    "'a' in ['a']",
    "[] == []",
    "[1, [2]] == [1, [2]]",
    "[1, 2].hasAll([])",
    "[].hasAny([1])",
  ],

  // ---------------------------------------------------------------- map
  map: [
    "{'a': 1}.size() == 1",
    "{'a': 1, 'b': 2}.keys() == ['a', 'b']",
    "{'b': 2, 'a': 1}.keys() == ['a', 'b']",
    "{'a': 1, 'b': 2}.values() == [1, 2]",
    "{'a': 1}.get('a', 0) == 1",
    "{'a': 1}.get('b', 0) == 0",
    "{'a': {'b': 1}}.get(['a', 'b'], 0) == 1",
    "{'a': 1}.get(['b', 'c'], 0) == 0",
    "'a' in {'a': 1}",
    "'b' in {'a': 1}",
    "{'a': 1}.a == 1",
    "{'a': 1}.b == 1",
    "{'a': 1}['a'] == 1",
    "{'a': 1}['b'] == 1",
    "{'a': 1}.keys().hasOnly(['a'])",
    "{'a': 1}.diff({'a': 1}).affectedKeys().size() == 0",
    "{'a': 1}.diff({'b': 2}).addedKeys() == ['a'].toSet()",
    "{'a': 1}.diff({'b': 2}).removedKeys() == ['b'].toSet()",
    "{'a': 1}.diff({'a': 2}).changedKeys() == ['a'].toSet()",
    "{'a': 1}.diff({'a': 1}).unchangedKeys() == ['a'].toSet()",
    "{'a': 1, 'b': 2}.diff({'a': 2}).affectedKeys() == ['a', 'b'].toSet()",
    "{}.size() == 0",
  ],

  // ---------------------------------------------------------------- set
  set: [
    "[1, 2].toSet().size() == 2",
    "[1, 2].toSet().union([3].toSet()) == [1, 2, 3].toSet()",
    "[1, 2].toSet().intersection([2, 3].toSet()) == [2].toSet()",
    "[1, 2].toSet().difference([2].toSet()) == [1].toSet()",
    "[1, 2].toSet().hasAll([1])",
    "[1, 2].toSet().hasAll([1, 3])",
    "[1, 2].toSet().hasAny([3, 1])",
    "[1, 2].toSet().hasOnly([1, 2, 3])",
    "[1, 2].toSet().hasAll([1].toSet())",
    "1 in [1, 2].toSet()",
    "3 in [1, 2].toSet()",
    "[1, 2].toSet().union([3]) == [1, 2, 3].toSet()",
    "[1, 2].toSet().toSet() == [1, 2].toSet()",
    "[].toSet().size() == 0",
  ],

  // ---------------------------------------------------------------- timestamp and duration
  timestamp: [
    "timestamp.date(2020, 1, 2) is timestamp",
    "timestamp.date(2020, 1, 2).year() == 2020",
    "timestamp.date(2020, 1, 2).month() == 1",
    "timestamp.date(2020, 1, 2).day() == 2",
    "timestamp.date(2020, 1, 2).dayOfWeek() == 4",
    "timestamp.date(2020, 1, 2).dayOfYear() == 2",
    "timestamp.date(2020, 1, 2).hours() == 0",
    "timestamp.value(1000) is timestamp",
    "timestamp.value(1000).toMillis() == 1000",
    "timestamp.value(1500).seconds() == 1",
    "timestamp.value(1500).nanos() == 500000000",
    "timestamp.date(2020, 1, 2).date() == timestamp.date(2020, 1, 2)",
    "timestamp.date(2020, 1, 2).time() == duration.value(0, 's')",
    "timestamp.value(1000) + duration.value(1, 's') == timestamp.value(2000)",
    "timestamp.value(2000) - timestamp.value(1000) == duration.value(1, 's')",
    "timestamp.value(2000) - duration.value(1, 's') == timestamp.value(1000)",
    "timestamp.date(2020, 13, 1) is timestamp",
    "timestamp.date(2020, 2, 30) is timestamp",
    "duration.value(1, 'w') == duration.value(7, 'd')",
    "duration.value(1, 'd') == duration.value(24, 'h')",
    "duration.value(1, 'h') == duration.value(60, 'm')",
    "duration.value(1, 'm') == duration.value(60, 's')",
    "duration.value(1, 's') == duration.value(1000000000, 'ns')",
    "duration.value(1, 'x') == duration.value(1, 's')",
    "duration.time(1, 2, 3, 4).seconds() == 3723",
    "duration.time(1, 2, 3, 4).nanos() == 4",
    "duration.abs(duration.value(-1, 's')) == duration.value(1, 's')",
    "duration.value(1, 's') + duration.value(1, 's') == duration.value(2, 's')",
    "request.time > timestamp.value(0)",
  ],

  // ---------------------------------------------------------------- latlng, math, hashing
  latlng: [
    "latlng.value(1.0, 2.0).latitude() == 1.0",
    "latlng.value(1.0, 2.0).longitude() == 2.0",
    "latlng.value(0.0, 0.0).distance(latlng.value(0.0, 0.0)) == 0.0",
    "latlng.value(0.0, 0.0).distance(latlng.value(1.0, 0.0)) > 111000.0",
    "latlng.value(91.0, 0.0) is latlng",
    "latlng.value(1, 2) is latlng",
  ],
  math: [
    "math.abs(-1) == 1",
    "math.abs(-1.5) == 1.5",
    "math.ceil(1.2) == 2",
    "math.ceil(1.2) is int",
    "math.floor(1.8) == 1",
    "math.round(1.5) == 2",
    "math.round(-1.5) == -2",
    "math.sqrt(4.0) == 2.0",
    "math.sqrt(4) == 2.0",
    "math.sqrt(-1.0) == 0.0",
    "math.isNaN(math.sqrt(-1.0))",
    "math.isInfinite(1.0)",
    "math.pow(2.0, 3.0) == 8.0",
    "math.abs(-9223372036854775807) == 9223372036854775807",
  ],
  hashing: [
    "hashing.md5('abc').toHexString().lower() == '900150983cd24fb0d6963f7d28e17f72'",
    "hashing.sha256('abc').toHexString().lower() == 'ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad'",
    "hashing.crc32('abc').toHexString().lower() == '352441c2'",
    "hashing.crc32c('abc').toHexString().lower() == '364b3fb7'",
    "hashing.md5('abc') is bytes",
    "hashing.md5('abc'.toUtf8()) == hashing.md5('abc')",
    "hashing.sha256('abc').size() == 32",
  ],

  // ---------------------------------------------------------------- path
  path: [
    "path('/a/b').size() == 2",
    "path('/a/b')[0] == 'a'",
    "path('a/b').size() == 2",
    "path('/a/b') == /a/b",
    "path('/a/b').bind({}) == path('/a/b')",
    "path('/a/$(x)').bind({'x': 'b'}) == path('/a/b')",
    "path('/a/$(x)').bind({'y': 'b'}) == path('/a/b')",
    "/databases/(default)/documents/a/b is path",
    "path('/a') + path('/b') == path('/a/b')",
    "string(path('/a/b')) == '/a/b'",
    "path(1) is path",
  ],

  // ---------------------------------------------------------------- request / resource shape
  request: [
    "request.auth == null",
    "request.method == 'get'",
    "request.path is path",
    "request.time is timestamp",
    "request.resource == null",
    "request.query == null",
    "resource == null",
    "resource.data == null",
    "request.auth.uid == 'x'",
    "request.bogus == null",
    "request.keys() is list",
  ],

  // ---------------------------------------------------------------- null / missing members
  nullness: [
    "{'a': 1}.b == null",
    "{'a': 1}['b'] == null",
    "null.a == null",
    "(null == null) && true",
    "true && null",
    "false && null",
    "true || null",
    "false || null",
    "!null",
    "null && null",
    "1 && true",
    "{'a': null}.a == null",
    "'a' in {'a': null}",
    "{'a': null}.keys() == ['a']",
    "{'a': null}.get('a', 1) == null",
  ],

  // ---------------------------------------------------------------- operators, short-circuit
  operators: [
    "true && true",
    "true && false",
    "(1 / 0 == 1) || true",
    "true || (1 / 0 == 1)",
    "false && (1 / 0 == 1)",
    "(1 / 0 == 1) && false",
    "true ? true : (1 / 0 == 1)",
    "false ? (1 / 0 == 1) : true",
    "1 == 1 ? true : false",
    "1 ? true : false",
    "!true == false",
    "-(-1) == 1",
    "-'a' == 'a'",
    "!1",
  ],

  // ---------------------------------------------------------------- debug()
  debug: ["debug(true)", "debug(false)", "debug(1) == 1", "debug([1, 2]).size() == 2"],

  // ---------------------------------------------------------------- pinned-down details
  //
  // Every claim below exists because a first pass left the exact behaviour open: which
  // rounding `math.round` does, what `hashing.crc32` returns, what a `set` answers `is`,
  // where a slice is in range and where it raises, and what `join` does to non-strings.
  detail: [
    "math.round(-1.5) == -1",
    "math.round(-1.4) == -1",
    "math.round(-1.6) == -2",
    "math.round(0.5) == 1",
    "math.round(1.5) is int",
    "math.floor(1.8) is float",
    "math.abs(-1) is int",
    "math.abs(-1.5) is float",
    "math.pow(2, 3) == 8.0",
    "math.pow(2.0, 3.0) is float",
    "math.sqrt(4) is float",
    "hashing.crc32('abc').size() == 4",
    "hashing.crc32('abc').size() == 8",
    "hashing.crc32('abc').toHexString() == '352441C2'",
    "hashing.crc32('abc').toHexString() == '00000000352441C2'",
    "hashing.crc32c('abc').toHexString() == '364B3FB7'",
    "hashing.md5('abc').toHexString() == '900150983CD24FB0D6963F7D28E17F72'",
    "hashing.sha256('abc').toBase64() == 'ungWv48Bz+pBQUDeXa4iI7ADYaOWF3qctBD/YfIAFa0='",
    "[1, 2].join(',') == '1,2'",
    "[1, 2].toSet() is bool",
    "[1, 2].toSet() is map",
    "[1, 2].toSet() is string",
    "[1, 2].toSet() is int",
    "[1, 2].toSet().size() is int",
    "[1, 2, 3][1:3] == [2, 3]",
    "[1, 2, 3][0:3] == [1, 2, 3]",
    "[1, 2, 3][0:0] == []",
    "[1, 2, 3][3:3] == []",
    "[1, 2, 3][-1:1] == [1]",
    "'abcdef'[0:6] == 'abcdef'",
    "'abcdef'[6:6] == ''",
    "'abcdef'[2:2] == ''",
    "'abcdef'[0:1] == 'a'",
    "'abc'.size() is int",
    "latlng.value(0.0, 0.0).distance(latlng.value(1.0, 0.0)) < 112000.0",
    "latlng.value(0.0, 0.0).distance(latlng.value(1.0, 0.0)) is float",
    "request.keys().hasAny(['auth'])",
    "request.keys().hasAny(['resource'])",
    "request.keys().hasAny(['query'])",
    "request.keys().hasAny(['method', 'path', 'time'])",
    "'resource' in request",
    "'query' in request",
    "'auth' in request",
    "string(path('/a/b')) == '/a/b'",
    "string([1, 2]) == '[1, 2]'",
    "string({'a': 1}) == '{a: 1}'",
    "string('a') == 'a'",
    "string(request.time) is string",
    "int('0x10') == 16",
    "int('-3') == -3",
    "int('') == 0",
    "int(9223372036854775807) == 9223372036854775807",
    "float('abc') == 0.0",
    "'a'.matches('A')",
    "'a'.matches('(?i)A')",
    "'aXb'.matches('a\\\\x58b')",
    "'a-b'.matches('[a\\\\-b]+')",
    "'a'.replace('a', '$0$0') == 'aa'",
    "'ab'.replace('(a)', '[$1]') == '[a]b'",
    "'abc'.matches('\\\\p{L}+')",
    "'a b'.matches('a\\\\sb')",
    "[1, 2].toSet().difference([2, 3].toSet()) == [1].toSet()",
    "[1, 2].toSet().hasOnly([1].toSet())",
    "([1, 2].toSet() == [1, 2].toSet()) && true",
    "{'a': 1}.diff({'a': 1}).affectedKeys().hasOnly([])",
    "path('/a/b').bind({'x': 'y'}) == path('/a/b')",
    "path('/a/{x}').bind({'x': 'b'}) == path('/a/b')",
    "'x' in path('/a/b')",
  ],

  // ---------------------------------------------------------------- byte encodings
  encoding: [
    "hashing.crc32('abc').toHexString() == 'C2412435'",
    "hashing.crc32('abc').toBase64() == 'NSRBwg=='",
    "hashing.crc32c('abc').toHexString() == 'B73F4B36'",
    "hashing.sha256('abc').toBase64() == 'ungWv48Bz+pBQUDeXa4iI7ADYaOWF3qctBD/YfIAFa0='",
    "hashing.sha256('abc').toBase64() == 'ungWv48Bz-pBQUDeXa4iI7ADYaOWF3qctBD_YfIAFa0='",
    "hashing.sha256('abc').toBase64() == 'ungWv48Bz+pBQUDeXa4iI7ADYaOWF3qctBD/YfIAFa0'",
    "'abc'.toUtf8().toBase64() == 'YWJj'",
    "'ab'.toUtf8().toBase64() == 'YWI='",
    "'ab'.toUtf8().toBase64() == 'YWI'",
    "'a'.toUtf8().toBase64() == 'YQ=='",
    "'a'.toUtf8().toBase64() == 'YQ'",
    "'\\u00ff\\u00fe'.toUtf8().toHexString() == 'C3BFC3BE'",
  ],

  // ---------------------------------------------------------------- slice bounds grid
  //
  // A first pass showed `[1, 2, 3][1:1]` yielding `[]` while `[1, 2, 3][0:0]` raises. The
  // grid decides exactly where a slice is in range for a list and for a string.
  slice: [
    "[1, 2, 3][0:0] is list",
    "[1, 2, 3][0:1] is list",
    "[1, 2, 3][0:2] is list",
    "[1, 2, 3][0:3] is list",
    "[1, 2, 3][0:4] is list",
    "[1, 2, 3][1:1] is list",
    "[1, 2, 3][1:2] is list",
    "[1, 2, 3][1:3] is list",
    "[1, 2, 3][2:2] is list",
    "[1, 2, 3][2:3] is list",
    "[1, 2, 3][3:3] is list",
    "[1, 2, 3][2:1] is list",
    "[1, 2, 3][-1:2] is list",
    "[1, 2, 3][1:-1] is list",
    "[][0:0] is list",
    "'abc'[0:0] is string",
    "'abc'[0:1] is string",
    "'abc'[0:3] is string",
    "'abc'[0:4] is string",
    "'abc'[1:1] is string",
    "'abc'[1:2] is string",
    "'abc'[2:2] is string",
    "'abc'[3:3] is string",
    "'abc'[2:1] is string",
    "''[0:0] is string",
    "[1, 2, 3][1:1] == []",
    "[1, 2, 3][2:2] == []",
    "'abc'[1:1] == ''",
    "'abc'[2:2] == ''",
  ],
};

/** @type {Claim[]} */
export const CLAIMS = Object.entries(AREAS).flatMap(([area, claims]) =>
  claims.map((claim, i) => ({ id: `${area}-${String(i + 1).padStart(3, "0")}`, area, claim })),
);

/** Areas in declaration order. */
export const AREA_NAMES = Object.keys(AREAS);
