"""Check that the records every closure cites exist and have not changed silently.

Every string in `spec/compatibility/closure/*.json` that starts with a repository path is a
reference. The path must exist; a `#fragment` must appear in the file; a sibling
`<name>Path` / `<name>Sha256` pair must match. Record files under `spec/` and
`conformance/` are pinned by SHA-256 in `spec/compatibility/closure/record-digests.json`,
so a cited record can only change together with an explicit lock update
(`--write`). A closure may not cite a suite that CI no longer runs (the
`RETIRED_SUITES` list in the compatibility-inventory workflow).
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CLOSURE_DIR = "spec/compatibility/closure"
LOCK = f"{CLOSURE_DIR}/record-digests.json"
WORKFLOW = ".github/workflows/compatibility-inventory.yml"
PREFIXES = ("spec/", "conformance/", "tools/", "docs/", "crates/", "verification/")
PINNED_PREFIXES = ("spec/", "conformance/")
REFERENCE = re.compile(r"^((?:spec|conformance|tools|docs|crates|verification)/[A-Za-z0-9_./()-]+)(#[^\s]+)?(?::|\s|$)")
DIGEST = re.compile(r"^[0-9a-f]{64}$")


@dataclass(frozen=True)
class Reference:
    closure: str
    path: str
    fragment: str | None


def _closures(root: Path) -> list[Path]:
    return sorted(
        path
        for path in (root / CLOSURE_DIR).glob("*.json")
        if path.name != Path(LOCK).name
    )


def _strings(value):
    if isinstance(value, dict):
        for item in value.values():
            yield from _strings(item)
    elif isinstance(value, list):
        for item in value:
            yield from _strings(item)
    elif isinstance(value, str):
        yield value


def _dicts(value):
    if isinstance(value, dict):
        yield value
        for item in value.values():
            yield from _dicts(item)
    elif isinstance(value, list):
        for item in value:
            yield from _dicts(item)


def closure_references(root: Path) -> list[Reference]:
    references = []
    for closure in _closures(root):
        document = json.loads(closure.read_text())
        for text in _strings(document):
            match = REFERENCE.match(text)
            if match:
                fragment = match.group(2)[1:] if match.group(2) else None
                references.append(Reference(closure.name, match.group(1), fragment))
    return references


def _markdown_anchors(text: str) -> set[str]:
    """GitHub-style heading anchors: lower case, punctuation dropped, spaces as hyphens."""
    anchors = set()
    for line in text.splitlines():
        match = re.match(r"^#{1,6}\s+(.*?)\s*#*\s*$", line)
        if match:
            slug = re.sub(r"[^\w\- ]", "", match.group(1).lower()).replace(" ", "-")
            anchors.add(slug)
    return anchors


def _fragment_present(target: Path, fragment: str) -> bool:
    text = target.read_text(errors="replace")
    if target.suffix == ".md":
        return fragment in _markdown_anchors(text)
    return fragment in text


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def build_lock(root: Path) -> dict:
    pinned = sorted(
        {
            ref.path
            for ref in closure_references(root)
            if ref.path.startswith(PINNED_PREFIXES) and (root / ref.path).is_file()
        }
    )
    return {
        "schemaVersion": 1,
        "note": "Generated by tools/compat-inventory/closure_records.py --write; regenerate in the commit that changes a cited record.",
        "records": {path: _sha256(root / path) for path in pinned},
    }


def retired_suites(root: Path) -> list[str]:
    workflow = (root / WORKFLOW).read_text()
    match = re.search(r"RETIRED_SUITES: \|\n((?:\s+\S.*\n)+)", workflow)
    if not match:
        return []
    return [
        line.strip()
        for line in match.group(1).splitlines()
        if line.strip() and not line.strip().startswith("#")
    ]


def check(root: Path) -> list[str]:
    problems = []
    references = closure_references(root)
    retired = retired_suites(root)
    for ref in references:
        target = root / ref.path
        if not target.exists():
            problems.append(f"{ref.closure}: {ref.path} is missing")
            continue
        if ref.fragment and target.is_file() and not _fragment_present(target, ref.fragment):
            problems.append(f"{ref.closure}: {ref.path}#{ref.fragment} names no entry in the file")
        if any(ref.path == suite or ref.path.startswith(f"{suite}/") for suite in retired):
            problems.append(f"{ref.closure}: {ref.path} is in a retired suite CI no longer runs")
    for closure in _closures(root):
        for entry in _dicts(json.loads(closure.read_text())):
            for key, value in entry.items():
                if not (key.endswith("Path") and isinstance(value, str)):
                    continue
                digest_key = f"{key[: -len('Path')]}Sha256"
                digest = entry.get(digest_key)
                if not (isinstance(digest, str) and DIGEST.match(digest)):
                    continue
                target = root / value
                if target.is_file() and _sha256(target) != digest:
                    problems.append(f"{closure.name}: {digest_key} differs from {value}")
    lock_path = root / LOCK
    if not lock_path.is_file():
        return [*problems, f"{LOCK} is missing; run closure_records.py --write"]
    pinned = json.loads(lock_path.read_text()).get("records", {})
    expected = build_lock(root)["records"]
    for path, digest in expected.items():
        if path not in pinned:
            problems.append(f"{path} is cited by a closure but not pinned in {LOCK}")
        elif pinned[path] != digest:
            problems.append(f"{path} digest differs from {LOCK}")
    for path in pinned:
        if path not in expected:
            problems.append(f"{path} is pinned in {LOCK} but no closure cites it")
    return list(dict.fromkeys(problems))


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--write", action="store_true")
    parser.add_argument("--root", type=Path, default=ROOT)
    args = parser.parse_args(argv)
    if args.write:
        (args.root / LOCK).write_text(json.dumps(build_lock(args.root), indent=2) + "\n")
        return 0
    problems = check(args.root)
    for problem in problems:
        print(problem, file=sys.stderr)
    references = closure_references(args.root)
    print(
        json.dumps(
            {
                "closures": len(_closures(args.root)),
                "references": len(references),
                "pinned": len(build_lock(args.root)["records"]),
                "problems": len(problems),
            }
        )
    )
    return 1 if problems else 0


if __name__ == "__main__":
    raise SystemExit(main())
